# .github/workflows/windows-build.yml
name: Build Windows EXE (Movidesk Client)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'movidesk/**'
      - 'backend.json'
      - '.github/workflows/windows-build.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo files (debug)
        shell: pwsh
        run: |
          Write-Host "=== TREE ==="
          Get-ChildItem -Recurse | ForEach-Object { $_.FullName }

      - name: Ensure backend.json present (create if missing)
        shell: pwsh
        run: |
          if (-not (Test-Path "backend.json")) {
            @'
{
  "backend_base": "https://web-production-ba1e.up.railway.app"
}
'@ | Out-File -Encoding utf8 backend.json
            Write-Host "backend.json criado com default."
          } else {
            Write-Host "backend.json já existe."
          }

      - name: Validate entrypoint
        shell: pwsh
        run: |
          if (-not (Test-Path "movidesk/main.py")) {
            Write-Error "ERRO: movidesk/main.py não encontrado. Ajuste o caminho no passo do PyInstaller."
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install ttkbootstrap requests pyinstaller

      - name: Detect icon (optional)
        shell: pwsh
        run: |
          if (Test-Path "icon.ico") {
            "ICON_FLAG=--icon icon.ico" | Out-File -FilePath $env:GITHUB_ENV -Append
            Write-Host "Usando icon.ico na raiz."
          } elseif (Test-Path "app_refactor/icon.ico") {
            "ICON_FLAG=--icon app_refactor/icon.ico" | Out-File -FilePath $env:GITHUB_ENV -Append
            Write-Host "Usando app_refactor/icon.ico."
          } else {
            "ICON_FLAG=" | Out-File -FilePath $env:GITHUB_ENV -Append
            Write-Host "Nenhum ícone encontrado; prosseguindo sem ícone."
          }

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconsole --onefile --name MovideskApp $env:ICON_FLAG --add-data "backend.json;." -p . movidesk/main.py

      - name: Package artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path out | Out-Null
          Copy-Item dist\MovideskApp.exe out\MovideskApp.exe
          Copy-Item backend.json out\backend.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MovideskApp_Windows
          path: out/*
